CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
CREATE USER '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_USERNAME}.* TO '${MYSQL_DATABASE}'@'%';
FLUSH PRIVILEGES;

SET NAMES 'utf8mb4' COLLATE 'utf8mb4_spanish_ci';